### ISSUE TITLE
Begin removing bluefin things

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/aurora#20]
- [x] Disable Bluefin Builds: https://github.com/ublue-os/bluefin/commit/0c4000045cd369009127b4bb238f62ce3bc66841
- [ ] Remove bluefin from build system: https://github.com/ublue-os/bluefin/commit/a3c2b039eb252c41c7ccd44ae8cd7c726c5742d9
- [x]  Cleanup bluefin system files: https://github.com/ublue-os/bluefin/commit/dbbc685d6f8200ba76fedce0ddaa1876bbb30df0
- [ ] Cleanup bluefin/gnome stuff in changelogs [changelogs.py](https://github.com/ublue-os/aurora/blob/main/.github/changelogs.py)
- [ ] Anywhere else in the Project

Bluefin commits are provided as reference, I also thought about putting the readme/other documentation here but that might be worth opening another issue

**Comment by RealVishy** [comment]
Yeah that's in the changelogs.py I'll add that to this tracking issue.

**Comment by RealVishy** [comment]
> I may have [removed the bluefin things](https://github.com/nisel11/aurora/commit/020092f7c497d26de0f801b0112c339cd2eb4957) but don't know do I did everything right, would like to hear some suggestions before pull request

pr it and but mark it as a draft, we can tr y building it to see if there's any issues.

**Comment by nisel11** [comment]
> > I may have [removed the bluefin things](https://github.com/nisel11/aurora/commit/020092f7c497d26de0f801b0112c339cd2eb4957) but don't know do I did everything right, would like to hear some suggestions before pull request
> 
> pr it but mark it as a draft, we can try building it to see if there's any issues.

I already [build it](https://github.com/nisel11/aurora/pkgs/container/aurora-dx)
