### ISSUE TITLE
[Proposal] Unhide Konsole but also keep Ptyxis

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/aurora#27]
Keep Ptyxis as a default though.

Windows has had Powershell and Command Prompt for ages, so why can't we ship two terminals?  Satisfies enjoyers of both terminals.

**Comment by RealVishy** [comment]
I'm happy to ship them both as flatpak so people can uninstall the one they don't like, as long as it doesn't interfere with their functionality.

**Comment by inffy** [comment]
Also the flatpak of Ptyxis is updated faster, just like we had like a month without a fixed Ptyxis version from Fedora when the container profiles "broke"

**Comment by etvt** [comment]
The only issue I found while using Konsole flatpak (and I assume the same would be with any other terminals running in flatpak), is that when you execute a command, in the titlebar it does not display that command, but it's always `flatpak-spawn`.

(Not sure if they could be patched in flathub to skip one level and display the next command only, but it would be nice...)

**Comment by etvt** [comment]
> (and I assume the same would be with any other terminals running in flatpak)

huhh, just checked, this is actually NOT the case: Ptyxis flatpak handles the flatpak environment correctly, displays the actual command in the titlebar and even changes title color to red when executing sudo... nice!

(I hope Konsole flatpak will also be corrected in the near future.)

But I think shipping both as flatpak is a good idea, that way ppl can remove the one they don't need.

**Comment by RealVishy** [comment]
I'll dogfood konsole for a week and let y'all know if I run into any issues with it.

**Comment by inffy** [comment]
Also important  ;)

With konsole we can easily beautify the fastfetch config, for example

![Image](https://github.com/user-attachments/assets/9ca0187b-689a-4e88-9b37-d3c8851f7e90)

🙃

**Comment by RealVishy** [comment]
Is there a way for us to have the `Ctrl+Alt+T` shortcut use the default terminal instead of being hardcoded to ptyxis?

**Comment by SirKiren** [comment]
> The only issue I found while using Konsole flatpak (and I assume the same would be with any other terminals running in flatpak), is that when you execute a command, in the titlebar it does not display that command, but it's always `flatpak-spawn`.
> 
> (Not sure if they could be patched in flathub to skip one level and display the next command only, but it would be nice...)

I haven’t found a way around this with the konsole flatpak either, but it’s the only issue I’ve noticed with the flatpak as well.
Personally I’d be in favor of leaving konsole in the image unless a workaround is found, it’s not exactly like it’s eating a ton of space.

**Comment by RealVishy** [comment]
IMO, worst case if they uninstall both, they can just reinstall them on discover. I understand the sentiment though, I'm a bit biased tho since I'd prefer to not have ptyxis at all tbh.

**Comment by inffy** [comment]
Maybe the best would be to include Konsole on the image and Ptyxis as flatpak (as the flatpak comes straight from upstream and not from Fedora).

Not sure where in the configs the ctrl+alt+t shortcut is set, tried to look for it but couldn't yet find where it is set for KDE.

**Comment by RealVishy** [comment]
https://github.com/ublue-os/aurora/pull/39

Konsole is back on the image, and i'm happy to remove ptyxis from the image and add it back as a flatpak.

**Comment by nicknamenamenick** [comment]
> [#39](https://github.com/ublue-os/aurora/pull/39)
> 
> Konsole is back on the image, and i'm happy to remove ptyxis from the image and add it back as a flatpak.

I'm a little more hesitant to do this because Flatpaks are part of the ISO and those who use Ptyxis might also configuration files (however I'm not sure), however I'm open to a PR for `:latest` before it hits `:stable`.  Also, I'm asking this a little prematurely and plan to write this up formally for the Aurora maintainers and Universal Blue members, but are you interested in getting right access to approve PRs for this repo soon?  We're looking for some additional contributors/maintainers for this project now that it's separated from Bluefin, so I thought I'd ask this now before I write it up officially to see how this goes since I'm used to writing Bazzite documentation not deputizing contributors. 😅

**Comment by RealVishy** [comment]
> I'm a little more hesitant to do this because Flatpaks are part of the ISO and those who use Ptyxis might also configuration files (however I'm not sure), but I'm open to a PR for `:latest` before it hits `:stable`.

sounds good, i'll make a pr for it.

> Also, I'm asking this a little prematurely and plan to write this up formally for the Aurora maintainers and Universal Blue members, but are you interested in getting right access to approve PRs for this repo soon? We're looking for some additional contributors/maintainers for this project now that it's separated from Bluefin, so I thought I'd ask this now before I write it up officially to see how this goes since I'm used to writing Bazzite documentation not deputizing contributors. 😅
> 
> EDIT: realized closing this means you can't respond to my question...

Yeah I'm down to help out more, I've been using aurora on both my devices so I'm happy to work on whatever's needed.
