### ISSUE TITLE
[Membership Request] RealVishy

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/aurora#47]
## Promotion

I'd like to nominate @RealVishy as an Aurora maintainer.  They have been sending in pull requests, marking down known issues, and supporting others in the Discord. As a minimum, they should have permission to review other pull requests.  If you are an Aurora or Universal Blue member/approver, please acknowledge this issue by posting a +1 if you are in favor of this. 

## Want to be an Aurora maintainer / active contributor?

There is also this [issue/announcement](https://github.com/ublue-os/aurora/issues/46) in regards to scouting for other Aurora maintainers. If you are interested in helping out with the project, then your contributions will be noticed and you may be granted maintainer status. We will be having similar membership posts for other active contributors soon.

**Comment by castrojo** [comment]
+1!

**Comment by p5** [comment]
+1!  Very helpful in the Discord and created various PRs

**Comment by NiHaiden** [comment]
+1

**Comment by nisel11** [comment]
+1
