### ISSUE TITLE
Remove kdeconnect and others  from default installation

### ISSUE THREAD

**Issue by arvindautar** [ublue-os/aurora#57]
I would like to propose the removal of the KDE Connect package from the default installation of our Linux distribution. While KDE Connect offers valuable features for syncing devices and enhancing productivity, not all users find it relevant to their needs. 

Many users may prefer alternative solutions or may not require the features provided by KDE Connect at all. Removing it from the default set of pre-installed applications would contribute to a more streamlined and user-centered experience, ensuring that users only encounter the tools that best meet their requirements.

Thank you for considering this request to enhance the overall usability of our system.

**Comment by arvindautar** [comment]
Same for, espesially for the packages that are already available as flatpak
- KNetAttach
-Thunderbird
- Kcontact
- InputLeap
-  Skanpage
 - Haruna
 -  Kwrite (kate is already installed, so no need for kwrite)

**Comment by tulilirockz** [comment]
good job writing a random prompt on chatGPT

**Comment by RealVishy** [comment]
Thunderbird and Haruna are already flatpaks so there's nothing stopping you from uninstalling them and using whatever you prefer. The other apps were layered because they **currently** have less functionality or aren't available as flatpaks
