### ISSUE TITLE
Can't skip `Authentication Required` despite `sudoers` edit

### ISSUE THREAD

**Issue by MLSci** [ublue-os/aurora#58]
### Describe the bug

Usually in situations such as opening apps like the `KDE Partition Manager`, an `Authentication Required` pops up and I’ll need to type the password to authenticate as myself. I’m the only person using this computer and would like a way to avoid having to type password every time doing things such as managing disks.

So far I’ve tried `sudo visudo` to edit `sudoers` by adding
`Defaults timestamp_timeout = -1`
`Defaults !authenticate`
or
`%wheel  ALL=(ALL)       NOPASSWD: ALL`
`my_name ALL=(ALL) NOPASSWD: ALL` at the end,
but none works.

### What did you expect to happen?

Ideally, once I log into the desktop session, I’d like to not have to type password again until I log out or reboot. Or at least when authentication is required, I can simply click `OK` or press `enter` to confirm I’m the admin like in Windows.

### Output of `bootc status`

```shell
Current staged state is native ostree
Current booted state is native ostree
Current rollback state is native ostree
```

### Output of `groups`

```shell
my-name wheel video usershares docker lxd incus-admin libvirt pcp plugdev adbusers nfs
```

### Extra information or context

```
Operating System: Aurora-DX 41
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.5-200.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® HD Graphics 630
```

**Comment by MLSci** [comment]
> Polkit is what controls privilege escalation for applications like KDE Partition Manager. You can create a global polkit rule to allow any user in the wheel group to automatically be granted privileges instead of asking each time.
> 
> Create a file named `/etc/polkit-1/rules.d/99-nopasswd_global.rules` with the following contents:
> 
> polkit.addRule(function(action, subject) { 
>   if (subject.isInGroup("wheel")) {
>     return polkit.Result.YES; 
>   } 
> });
> This should make it so apps like KDE Partition Manager won't ask for a password.
> 
> See https://wiki.archlinux.org/title/Polkit#Examples for more examples and info.

Thanks for the detailed instruction. I always thought `sudo` is the only way to control privilege escalation. So now polkit has replaced the role of `sudo`, or .. ? Is this why editing `sudoers` doesn't work but editing polkit works?

**Comment by ledif** [comment]
Although not entirely accurate, you can view sudo as suited for privilige escalation of command-line applications and polkit suited for privilge escalation of GUI applications. This is not completely true, but it can be useful for determining which of the two is probably responsible for the app you're trying to run.

**Comment by MLSci** [comment]
Both `sudo` and polkit need to be edited to achieve the purpose for all (CLI and GUI) use cases. In the old days `sudo` alone is sufficient (?) since most apps are CLI apps.

**Comment by MLSci** [comment]
Both `sudo` and polkit need to be edited to achieve the purpose for all (CLI and GUI) use cases. In the old days `sudo` alone is sufficient (?) since most apps are CLI apps.
