### ISSUE TITLE
ISO secrets need to be updated

### ISSUE THREAD

**Issue by castrojo** [ublue-os/aurora#6]
The secrets for pushing ISOs to R2 are done per repository, these need to be set in this repo and then updated in cloudflare: 

![Image](https://github.com/user-attachments/assets/40d2ef39-1509-4991-a199-4dcdf9b23bb9)

**Comment by NiHaiden** [comment]
I need permissions to update these, please. @castrojo

**Comment by NiHaiden** [comment]
The repo has new secrets now.

**Comment by castrojo** [comment]
Ok testing a push here: https://github.com/ublue-os/aurora/actions/runs/12224334928
